# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies & Build Website
      run: |
        yarn install
        yarn run build
    - name: Setup Github ENV
      run: |
        git config --global user.email "jubayerarefin@users.noreply.github.com"
        git config --global user.name "jubayerarefin"
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.5.4 # This step installs the ssh client into the workflow run. There's many options available for this on the action marketplace.
      with:
        ssh-private-key: ${{ secrets.Deploy_Key_Private }}
    - name: Set ENV & Deploy Website
      env:
        GIT_USER: 'jubayerarefin'
        CURRENT_BRANCH: 'master'
        USE_SSH: true
      run: yarn run deploy
